### ISSUE TITLE
Header needed for 'Indicator' pages and 'Fundamental Questions'

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/Aid-Watch#17]
Looks like we need this Header style in place for 'Iindicator' 

e.g.
http://dev.awptheme.peacegeeks.org/indicators/ceasefire
http://dev.awptheme.peacegeeks.org/indicators/pledges

I *think* that should be the only other case where this is needed.

**Comment by PeaceGeeks** [comment]
Also
http://dev.awptheme.peacegeeks.org/content/what-do-we-know-about-aid-palestine-0
http://dev.awptheme.peacegeeks.org/content/who-responsible-rebuilding-gaza

**Comment by PeaceGeeks** [comment]
None of Nora's images fir the size requirements. Is there anyway to relax the req's on images?

**Comment by beyondes** [comment]
1. If we want to use the cropping tool module, we need to have high quality images, 1196 x 486 px
2. Or to upload the image as it is and enlarge it with drupal scale and crop image style.

but uploading small images will lead to pixelate images, since we will enlarge small images to the document width. we prefer to upload big images.

please let me know what solutions is better for you or awp
